#Use a Python 3.10 slim image as the base
FROM python:3.12-slim

# Set environment variables
ENV PYTHONUNBUFFERED 1
WORKDIR /app

# Copy and install only the frontend requirements
COPY src/frontend/requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

# Copy only the necessary frontend source code
COPY src/frontend /app/src/frontend