from pydantic import BaseModel


class Query(BaseModel):
    """
    The input question sent by the user.
    Attributes:
        text (str): The natural language question to be answered.
    """
    query: str

class Response(BaseModel):
    """
    The response generated by the RAG system.
    Attributes:
        query (str): The original query.
        answer (str): The generated answer.
    """
    query: str
    answer: str

class Health_Status(BaseModel):
    message: str
    status: str

